apiVersion: v1
kind: Service
metadata:
  name: sample-js
spec:
  selector:
    app: sample-js
  ports:
    - port: 8080
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-js
spec:
  #nodeName: foo-node (https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/)
  replicas: 4
  selector:
    matchLabels:
      app: sample-js
  template:
    metadata:
      labels:
        app: sample-js
    spec:
      containers:
        - name: sample-js
          image: samuelparacontato/sample-js:1.0.0
          ports:
            - containerPort: 3000
          imagePullPolicy: Always